-- =============================================================================
-- YagnaTech LMS — Supabase / Postgres schema bootstrap
-- File 01: schemas + ENUM types
-- Source: YagnaTechOrg/DATABASE.md (MySQL 8 + Sequelize, reverse-engineered)
-- =============================================================================
-- Translation notes:
--   * MySQL  STRING       -> Postgres VARCHAR(255)
--   * MySQL  STRING(N)    -> VARCHAR(N)
--   * MySQL  TEXT('long') -> TEXT
--   * MySQL  DATE/DATETIME (Sequelize DATE) -> TIMESTAMPTZ
--   * MySQL  DATEONLY     -> DATE
--   * MySQL  JSON         -> JSONB
--   * MySQL  TINYINT      -> SMALLINT
--   * MySQL  AUTO_INCREMENT -> GENERATED BY DEFAULT AS IDENTITY
--   * MySQL  ENUM(...)    -> Postgres CREATE TYPE ... AS ENUM
-- =============================================================================

CREATE SCHEMA IF NOT EXISTS lucy_devdb;
CREATE SCHEMA IF NOT EXISTS lms_admin;

-- -----------------------------------------------------------------------------
-- ENUM TYPES (lucy_devdb)
-- -----------------------------------------------------------------------------
DO $$ BEGIN
  CREATE TYPE lucy_devdb.gender_enum AS ENUM ('male', 'female');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  CREATE TYPE lucy_devdb.education_level_enum AS ENUM ('inter', 'bachelor', 'master', 'phd', 'other');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  CREATE TYPE lucy_devdb.profile_status_enum AS ENUM ('active', 'inactive', 'pending');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  CREATE TYPE lucy_devdb.role_enum AS ENUM ('student', 'instructor', 'admin', 'auditor');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  CREATE TYPE lucy_devdb.enrollment_status_enum AS ENUM ('enrolled', 'in-progress', 'completed', 'dropped');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  CREATE TYPE lucy_devdb.assessment_type_enum AS ENUM ('pre', 'post');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  CREATE TYPE lucy_devdb.assessment_status_enum AS ENUM (
    'not-started', 'available', 'in-progress', 'completed', 'expired'
  );
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  CREATE TYPE lucy_devdb.question_severity_enum AS ENUM ('easy', 'medium', 'hard');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

-- pre_assessment_registrations.gender / selectedProgram / assessmentStatus
-- The Node code references GENDERS / PROGRAMS / ASSESSMENT_STATUSES constants.
-- Values below mirror what is observable from program_requests + service logic.
DO $$ BEGIN
  CREATE TYPE lucy_devdb.preassess_gender_enum AS ENUM (
    'male', 'female', 'other', 'prefer-not-to-say'
  );
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  CREATE TYPE lucy_devdb.program_enum AS ENUM (
    'AI Frontier Program',
    'AI Frontier Plus Program',
    'Elite AI Residency'
  );
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  CREATE TYPE lucy_devdb.preassess_status_enum AS ENUM (
    'registered', 'in-progress', 'submitted', 'evaluated', 'expired'
  );
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  CREATE TYPE lucy_devdb.program_request_status_enum AS ENUM (
    'sent', 'accepted', 'rejected', 'cancelled'
  );
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

-- -----------------------------------------------------------------------------
-- ENUM TYPES (lms_admin)
-- -----------------------------------------------------------------------------
DO $$ BEGIN
  CREATE TYPE lms_admin.language_direction_enum AS ENUM ('ltr', 'rtl');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
