-- =============================================================================
-- YagnaTech LMS — Supabase / Postgres schema bootstrap
-- File 03: lms_admin tables (Laravel-style LMS content + progress)
-- =============================================================================
-- Naming convention: snake_case (matches admin-service models).
-- All tables use created_at / updated_at (Laravel convention).
-- Cross-schema FKs to lucy_devdb are NOT enforced (matches the current
-- admin-service contract using the second Sequelize handle authDb).
-- NOTE: lms_admin.user_id columns store VARCHAR userIds from lucy_devdb.users
--       — DATABASE.md §9.7 flags the original BIGINT/STRING mismatch as a
--       latent bug. We use VARCHAR(255) here to remove the coercion risk.
-- =============================================================================

-- -----------------------------------------------------------------------------
-- users  (Laravel-style; distinct from lucy_devdb.users)
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS lms_admin.users (
  id                INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  role              VARCHAR(100) NOT NULL,
  email             VARCHAR(255) NOT NULL UNIQUE,
  status            INTEGER,
  name              VARCHAR(255),
  phone             VARCHAR(255),
  website           VARCHAR(255),
  skills            TEXT,
  facebook          TEXT,
  twitter           VARCHAR(255),
  linkedin          VARCHAR(255),
  address           VARCHAR(255),
  college_name      VARCHAR(255),
  college_id        VARCHAR(255),  -- logical FK -> lucy_devdb.colleges.clgId
  about             TEXT,
  biography         TEXT,
  educations        TEXT,
  photo             VARCHAR(255),
  email_verified_at TIMESTAMPTZ,
  password          VARCHAR(255),  -- nullable in source; flagged in §9.7
  remember_token    VARCHAR(100),
  paymentkeys       TEXT,
  video_url         VARCHAR(255),
  created_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at        TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- -----------------------------------------------------------------------------
-- categories  (self-referencing tree)
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS lms_admin.categories (
  id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  parent_id     INTEGER REFERENCES lms_admin.categories (id) ON UPDATE CASCADE ON DELETE SET NULL,
  title         VARCHAR(255) NOT NULL,
  slug          VARCHAR(255),
  icon          VARCHAR(255),
  sort          INTEGER DEFAULT 0,
  status        VARCHAR(50) DEFAULT 'active',
  keywords      VARCHAR(400),
  description   VARCHAR(500),
  thumbnail     VARCHAR(255),
  category_logo VARCHAR(255),
  clg_ids       JSONB DEFAULT '[]'::jsonb,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- -----------------------------------------------------------------------------
-- courses  (lms_admin flavor)
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS lms_admin.courses (
  id                    INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title                 VARCHAR(255) NOT NULL,
  slug                  VARCHAR(255),
  short_description     TEXT,
  user_id               INTEGER REFERENCES lms_admin.users (id) ON UPDATE CASCADE ON DELETE SET NULL,
  category_id           INTEGER REFERENCES lms_admin.categories (id) ON UPDATE CASCADE ON DELETE SET NULL,
  course_type           VARCHAR(50) DEFAULT 'general',
  status                VARCHAR(50) DEFAULT 'active',
  level                 VARCHAR(50),
  language              VARCHAR(50),
  is_paid               BOOLEAN DEFAULT FALSE,
  is_best               BOOLEAN DEFAULT FALSE,
  price                 REAL DEFAULT 0,
  discounted_price      REAL DEFAULT 0,
  discount_flag         BOOLEAN DEFAULT FALSE,
  enable_drip_content   BOOLEAN DEFAULT FALSE,
  drip_content_settings TEXT,
  meta_keywords         TEXT,
  meta_description      TEXT,
  thumbnail             VARCHAR(255),
  banner                VARCHAR(255),
  preview               VARCHAR(255),
  description           TEXT,
  requirements          TEXT,
  outcomes              TEXT,
  faqs                  TEXT,
  instructor_ids        TEXT,           -- CSV / JSON-as-text in source
  clg_ids               JSONB DEFAULT '[]'::jsonb,
  average_rating        REAL DEFAULT 0,
  expiry_period         INTEGER,
  created_at            TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at            TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- -----------------------------------------------------------------------------
-- sections
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS lms_admin.sections (
  id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id    INTEGER,
  course_id  INTEGER REFERENCES lms_admin.courses (id) ON UPDATE CASCADE ON DELETE CASCADE,
  title      VARCHAR(255),
  sort       INTEGER,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- -----------------------------------------------------------------------------
-- lessons
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS lms_admin.lessons (
  id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title           VARCHAR(255),
  user_id         INTEGER,
  course_id       INTEGER REFERENCES lms_admin.courses (id) ON UPDATE CASCADE ON DELETE CASCADE,
  section_id      INTEGER REFERENCES lms_admin.sections (id) ON UPDATE CASCADE ON DELETE CASCADE,
  lesson_type     VARCHAR(255),
  duration        VARCHAR(255),
  total_mark      INTEGER,
  pass_mark       INTEGER,
  retake          INTEGER,
  lesson_src      VARCHAR(255),
  attachment      TEXT,
  attachment_type VARCHAR(255),
  video_type      TEXT,
  thumbnail       VARCHAR(255),
  is_free         INTEGER,
  sort            INTEGER,
  description     TEXT,
  summary         TEXT,
  status          INTEGER,
  created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- -----------------------------------------------------------------------------
-- questions  (quiz flavor — quiz_id is logical FK -> lessons.id where
--             lesson_type = 'quiz')
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS lms_admin.questions (
  id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  quiz_id    INTEGER,
  title      TEXT,
  type       VARCHAR(255),
  answer     TEXT,
  options    TEXT,
  sort       INTEGER,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- -----------------------------------------------------------------------------
-- quiz_submissions
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS lms_admin.quiz_submissions (
  id             INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  quiz_id        INTEGER,
  user_id        VARCHAR(255),
  correct_answer TEXT,
  wrong_answer   TEXT,
  submits        TEXT,
  score          INTEGER,
  total          INTEGER,
  created_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at     TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- -----------------------------------------------------------------------------
-- settings  (key-value store)
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS lms_admin.settings (
  id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  type        VARCHAR(255),
  description TEXT,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- -----------------------------------------------------------------------------
-- live_classes
--   user_id widened to BIGINT in MySQL by boot ALTER; here VARCHAR(255)
--   to align with lucy_devdb.users.userId (see file-header note).
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS lms_admin.live_classes (
  id                   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id              VARCHAR(255),
  course_id            INTEGER REFERENCES lms_admin.courses (id) ON UPDATE CASCADE ON DELETE CASCADE,
  class_topic          VARCHAR(255),
  provider             VARCHAR(255),
  class_date_and_time  TIMESTAMPTZ,
  additional_info      TEXT,
  note                 TEXT,
  created_at           TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at           TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- -----------------------------------------------------------------------------
-- coupons
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS lms_admin.coupons (
  id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id    INTEGER NOT NULL,
  code       VARCHAR(255) NOT NULL UNIQUE,
  discount   INTEGER NOT NULL,
  expiry     BIGINT NOT NULL,           -- epoch millis (matches source)
  status     SMALLINT DEFAULT 1,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- -----------------------------------------------------------------------------
-- certificates
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS lms_admin.certificates (
  id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id         VARCHAR(255),
  course_id       INTEGER REFERENCES lms_admin.courses (id) ON UPDATE CASCADE ON DELETE SET NULL,
  identifier      VARCHAR(100) UNIQUE,
  title           VARCHAR(255),
  description     TEXT,
  template_image  VARCHAR(255),
  status          SMALLINT DEFAULT 1,
  issued_at       TIMESTAMPTZ,
  created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- -----------------------------------------------------------------------------
-- pre_assessment_results
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS lms_admin.pre_assessment_results (
  id               INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id          VARCHAR(255) NOT NULL,
  program_id       INTEGER,
  score            REAL NOT NULL DEFAULT 0,
  passed           BOOLEAN NOT NULL DEFAULT FALSE,
  duration_seconds INTEGER,
  created_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at       TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- -----------------------------------------------------------------------------
-- user_progress
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS lms_admin.user_progress (
  id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id         VARCHAR(255) NOT NULL,
  program_id      INTEGER NOT NULL,
  course_id       INTEGER,
  last_lesson_id  INTEGER,
  enrolled        BOOLEAN NOT NULL DEFAULT FALSE,
  created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (user_id, program_id)
);

-- -----------------------------------------------------------------------------
-- lesson_completions
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS lms_admin.lesson_completions (
  id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id    VARCHAR(255) NOT NULL,
  course_id  INTEGER NOT NULL,
  lesson_id  INTEGER NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (user_id, lesson_id)
);

-- -----------------------------------------------------------------------------
-- lesson_watch_progress
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS lms_admin.lesson_watch_progress (
  id               INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id          VARCHAR(255) NOT NULL,
  course_id        INTEGER NOT NULL,
  lesson_id        INTEGER NOT NULL,
  current_duration INTEGER NOT NULL DEFAULT 0,
  created_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (user_id, lesson_id)
);

-- -----------------------------------------------------------------------------
-- languages
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS lms_admin.languages (
  id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name       VARCHAR(100) NOT NULL UNIQUE,
  code       VARCHAR(20),
  direction  lms_admin.language_direction_enum NOT NULL DEFAULT 'ltr',
  is_default BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- -----------------------------------------------------------------------------
-- forums  (self-referencing: parent_id NULL = question, set = reply)
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS lms_admin.forums (
  id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  course_id   INTEGER REFERENCES lms_admin.courses (id) ON UPDATE CASCADE ON DELETE CASCADE,
  user_id     VARCHAR(255),
  parent_id   INTEGER REFERENCES lms_admin.forums (id) ON UPDATE CASCADE ON DELETE CASCADE,
  title       VARCHAR(255),
  description TEXT,
  likes       TEXT,
  dislikes    TEXT,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- -----------------------------------------------------------------------------
-- forum_reports
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS lms_admin.forum_reports (
  id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  forum_id   INTEGER NOT NULL
    REFERENCES lms_admin.forums (id) ON UPDATE CASCADE ON DELETE CASCADE,
  user_id    VARCHAR(255) NOT NULL,
  reason     TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (forum_id, user_id)
);

-- -----------------------------------------------------------------------------
-- seo_fields
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS lms_admin.seo_fields (
  id               INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  course_id        INTEGER,
  route            VARCHAR(255),
  name_route       VARCHAR(255),
  meta_title       VARCHAR(255),
  meta_description TEXT,
  meta_keywords    TEXT,
  meta_robot       VARCHAR(100),
  canonical_url    VARCHAR(255),
  custom_url       VARCHAR(255),
  json_ld          TEXT,
  og_title         VARCHAR(255),
  og_description   TEXT,
  og_image         VARCHAR(255),
  created_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at       TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- -----------------------------------------------------------------------------
-- updated_at auto-touch trigger for every lms_admin table that has it
-- -----------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION lms_admin.touch_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at := now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DO $$
DECLARE r RECORD;
BEGIN
  FOR r IN
    SELECT table_name FROM information_schema.columns
     WHERE table_schema = 'lms_admin' AND column_name = 'updated_at'
     GROUP BY table_name
  LOOP
    EXECUTE format(
      'DROP TRIGGER IF EXISTS trg_touch_updated_at ON lms_admin.%I;
       CREATE TRIGGER trg_touch_updated_at BEFORE UPDATE ON lms_admin.%I
         FOR EACH ROW EXECUTE FUNCTION lms_admin.touch_updated_at();',
      r.table_name, r.table_name);
  END LOOP;
END $$;
